### PR TITLE
Fix prev when reading first token_type=prev

### PR DESCRIPTION
**Pull request by ahuarte47**
This PR fixes https://github.com/stac-utils/pgstac/issues/140

### CODE REVIEW

**Comment by ahuarte47** [comment]
That following SQL queries should return same result. `prev` should be null for both. Without this fix the second one defines `prev` as "prev:pgstac-test-item-0011".

```
SELECT search(
    '{ 
       "collections": ["pgstac-test-collection"], 
       "limit": 10, 
       "sortby":[{"field": "id", "direction": "asc"}]
     }'
)

SELECT search(
    '{ 
      "collections": ["pgstac-test-collection"], 
      "limit": 10, 
      "sortby":[{"field": "id", "direction": "asc"}], 
      "token": "prev:pgstac-test-item-0011"
     }'
)
```

**Comment by drnextgis** [comment]
Great job @ahuarte47! But in order to make tests passed we need to do some extra work:

1. Update version [here](https://github.com/stac-utils/pgstac/blob/566974958c889a215b5fa6fa81d89ec431a60fcf/pypgstac/pypgstac/version.py#L2)
2. Update version [here](https://github.com/stac-utils/pgstac/blob/566974958c889a215b5fa6fa81d89ec431a60fcf/sql/999_version.sql#L1)
3. Create file `pypgstac/pypgstac/migrations/pgstac.0.6.6-0.6.7.sql` and put there new version of the function you modified
4. Create file `pypgstac/pypgstac/migrations/pgstac.0.6.7.sql` (I believe we can simply copy it from `pgstac.0.6.6.sql` and update the relevant part)

I've made all those steps locally and can confirm that all tests are passed:

```
$ ./scripts/cibuild
...
Running PGTap Tests on Temp DB 1
Checking if any tests are not ok on db postgresql://username:password@localhost:5432/migra_from
All PGTap Tests Passed!
Using Migra to test for any differences between incrementally migrated DB and DB created with latest base migration.
No differences found.
Running pypgstac tests...
Creating pgstac_dev_run ... done
Running mypy...
Success: no issues found in 16 source files
Running black...
All done! ✨ 🍰 ✨
16 files would be left unchanged.
Running flake8...
Running unit tests...
==================================================================== test session starts =====================================================================
platform linux -- Python 3.8.12, pytest-5.4.3, py-1.11.0, pluggy-0.13.1
rootdir: /opt/src/pypgstac
collected 72 items                                                                                                                                           

pypgstac/tests/test_load.py ...................                                                                                                        [ 26%]
pypgstac/tests/hydration/test_base_item.py .                                                                                                           [ 27%]
pypgstac/tests/hydration/test_dehydrate.py .............                                                                                               [ 45%]
pypgstac/tests/hydration/test_dehydrate_pg.py .............                                                                                            [ 63%]
pypgstac/tests/hydration/test_hydrate.py .............                                                                                                 [ 81%]
pypgstac/tests/hydration/test_hydrate_pg.py .............                                                                                              [100%]

=============================================================== 72 passed in 98.37s (0:01:38) ================================================================
Checking if there are any staged migrations.
Checking whether base sql migration exists...
Congratulations! All pypgstac tests pass.

```

**Comment by ahuarte47** [comment]
Thank you very much @drnextgis for your advices !!!!

**Comment by drnextgis** [comment]
@bitner could you please trigger the pipeline?

**Comment by bitner** [comment]
@drnextgis @ahuarte47 There is actually a utility that can be used to help create the migrations file that is necessary. You can take a look at [the release process docs](https://github.com/stac-utils/pgstac/blob/main/CONTRIBUTING.md#release-process). `scripts/stageversion <versionnumber>` will actually compare the new version and the old version and create a migration with the differences. This auto-generated file has the suffix ".staged" and should be reviewed before removing the suffix to make sure that everything looks correct.
> Great job @ahuarte47! But in order to make tests passed we need to do some extra work:
> 
> 1. Update version [here](https://github.com/stac-utils/pgstac/blob/566974958c889a215b5fa6fa81d89ec431a60fcf/pypgstac/pypgstac/version.py#L2)
> 2. Update version [here](https://github.com/stac-utils/pgstac/blob/566974958c889a215b5fa6fa81d89ec431a60fcf/sql/999_version.sql#L1)
> 3. Create file `pypgstac/pypgstac/migrations/pgstac.0.6.6-0.6.7.sql` and put there new version of the function you modified
> 4. Create file `pypgstac/pypgstac/migrations/pgstac.0.6.7.sql` (I believe we can simply copy it from `pgstac.0.6.6.sql` and update the relevant parts)
> 
> I've made all those steps locally and can confirm that all tests are passed:
> 
> ```
> $ ./scripts/cibuild
> ...
> Running PGTap Tests on Temp DB 1
> Checking if any tests are not ok on db postgresql://username:password@localhost:5432/migra_from
> All PGTap Tests Passed!
> Using Migra to test for any differences between incrementally migrated DB and DB created with latest base migration.
> No differences found.
> Running pypgstac tests...
> Creating pgstac_dev_run ... done
> Running mypy...
> Success: no issues found in 16 source files
> Running black...
> All done! ✨ 🍰 ✨
> 16 files would be left unchanged.
> Running flake8...
> Running unit tests...
> ==================================================================== test session starts =====================================================================
> platform linux -- Python 3.8.12, pytest-5.4.3, py-1.11.0, pluggy-0.13.1
> rootdir: /opt/src/pypgstac
> collected 72 items                                                                                                                                           
> 
> pypgstac/tests/test_load.py ...................                                                                                                        [ 26%]
> pypgstac/tests/hydration/test_base_item.py .                                                                                                           [ 27%]
> pypgstac/tests/hydration/test_dehydrate.py .............                                                                                               [ 45%]
> pypgstac/tests/hydration/test_dehydrate_pg.py .............                                                                                            [ 63%]
> pypgstac/tests/hydration/test_hydrate.py .............                                                                                                 [ 81%]
> pypgstac/tests/hydration/test_hydrate_pg.py .............                                                                                              [100%]
> 
> =============================================================== 72 passed in 98.37s (0:01:38) ================================================================
> Checking if there are any staged migrations.
> Checking whether base sql migration exists...
> Congratulations! All pypgstac tests pass.
> ```

**Review by bitner — APPROVED** [review]
Looks good. Thanks @ahuarte47 @drnextgis

**Comment by ahuarte47** [comment]
Thanks @bitner !!!

**Pull request merged**
