### PR TITLE
add tests for collections search links

### PR DESCRIPTION
**Pull request by vincentsarago**
while working on https://github.com/stac-utils/stac-fastapi-pgstac/pull/155 we encountered some strange behaviour with the next/prev links returned by pgstac

The first commit of this PR adds tests showing what I was expecting from pgstac 

cc @bitner 

Note: in tipg this is how we determine next/prev links https://github.com/developmentseed/tipg/blob/ea1ef949873abb7886811dce85a47913f38e3e38/tipg/collections.py#L783-L788

### CODE REVIEW

**Comment by vincentsarago** [comment]
🤔 well tests pass!

**Comment by vincentsarago** [comment]
@bitner I'm not sure to understand how the CI is design, thus I'm not sure that pgtap was ran with my last commit

**Comment by bitner** [comment]
Yeah, it doesn't look like tests ran at all.

**Review by bitner — APPROVED** [review]

**Comment by drnextgis** [comment]
In 'Files changed' tab I see changes that were already merged to the `main` branch, like this https://github.com/stac-utils/pgstac/commit/b73d5703e4b179cdaad185d6795b66efa3bc7087.

**Comment by drnextgis** [comment]
Ah that makes sense because it was never included in the migrations.

**Pull request merged**
