### PR TITLE
Add numberReturned and numberMatched fields to ItemCollection

### PR DESCRIPTION
**Pull request by drnextgis**
ref: https://github.com/radiantearth/stac-api-spec/issues/396
ref: https://github.com/stac-utils/stac-fastapi/issues/478

The context extension is deprecated.

### CODE REVIEW

**Comment by drnextgis** [comment]
@bitner please review and let me know whether you believe we should also consider updating `collection_search`?

**Comment by vincentsarago** [comment]
thanks @drnextgis 🙏

**Review by vincentsarago — APPROVED** [review]

**Comment by bitner** [comment]
@drnextgis This looks great, if you are up to changing in collection_search as well, that would be awesome. I don't have strong feelings about this, but do we want an option to use the deprecated context still for any clients that continue to expect that?

**Comment by drnextgis** [comment]
`collection_search` has been updated, and tests have been adjusted

**Comment by drnextgis** [comment]
> @drnextgis This looks great, if you are up to changing in collection_search as well, that would be awesome. I don't have strong feelings about this, but do we want an option to use the deprecated context still for any clients that continue to expect that?

I agree, I don't have strong feelings either. Documenting it as a backwards incompatible change in the changelog should suffice. In stac-pydantic it was [removed](https://github.com/stac-utils/stac-pydantic/pull/138) by @vincentsarago.

**Comment by vincentsarago** [comment]
> I don't have strong feelings either. Documenting it as a backwards incompatible change in the changelog should suffice. In stac-pydantic it was https://github.com/stac-utils/stac-pydantic/pull/138 by @vincentsarago.

The ContextExtension is deprecated and will be removed in next version of stac-fastapi https://github.com/stac-utils/stac-fastapi/issues/649

**Review by bitner — APPROVED** [review]

**Pull request merged**
